---
version: "3.7"
services:
  mealie:
    image: hkotel/mealie:v1.7.0
    container_name: mealie
    restart: always
    ports:
      - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 750M
    environment:
     # Set Frontend ENV Variables Here
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - TRUSTED_PROXIES
      - LETSENCRYPT_HOST
      # Set Backend ENV Variables Here
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_AUTH_STRATEGY
      - SMTP_FROM_NAME
      - SMTP_FROM_EMAIL
      - SMTP_USER
      - SMTP_PASSWORD
      - SECURITY_MAX_LOGIN_ATTEMPTS
      - SECURITY_USER_LOCKOUT_TIME
      - ALLOW_SIGNUP
      - DEFAULT_EMAIL
    volumes:
      - /mnt/data/all/mealie-data:/app/data/ # 
    networks: ["net"]

networks:
  net:
    external: true

