version: "3.8"
services:

  NCDatabase:
    image: "postgres:13.4"
    hostname: "${POSTGRES_HOST}"
    volumes:
      - "/mnt/data/postgres-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    restart: "always"
    networks: ["common"]

  Nextcloud:
    image: "nextcloud:22.2.8-apache"
    volumes:
      - "/mnt/data/nextcloud-server:/var/www/html"
      - "/mnt/data/all/nextcloud-data:/var/www/html/data"
    environment:
      - LETSENCRYPT_HOST
      - VIRTUAL_HOST
      - TRUSTED_PROXIES
      - OVERWRITEPROTOCOL
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_NAME
      - SMTP_PASSWORD
      - MAIL_FROM_ADDRESS
      - NEXTCLOUD_TRUSTED_DOMAINS
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
    depends_on:
      - "NCDatabase"
    restart: "always"
    networks: ["net", "common"]

  Redis:
    image: "redis:7.0.0"
    networks: ["common"]
    hostname: "redis"
    ports: 
      - "6379:6379"
    restart: "always"
    environment:
      - REDIS_PASSWORD

networks:
  net:
    external: true
  common:

